function E2=E2eval(t,q,qd,par,J,dpP0,dpP1,dpP2,bp,ux,uy,uz,P,...
    A1,apppsa,atpppsa)
%Enter terms for (Eqd)q*qd
[nq,nh,nd,nv,nu,nw,nx,m,g,F,k,c,phi,amp,om,sf,utol,Btol,Htol,...
    mode,integ,hmax]=parPart(par);
[r,p,a,s]=qPart(q);
[rd,pd,ad,sd]=qdPart(qd)
[thet,thetd,thetdd]=Steer(t,par);
p2=[cos(thet/2);uz*sin(thet/2)];
AT=ATran(p);
A2=ATran(p2);
appp=[0;a];
atppp=[0;P*a];
at=AT*A1*A2*atppp;
 c2=-(rd'+pd'*(BTran(p,bp)-s*BTran(p,A1*uz)+BTran(p,A1*A2*appp))'+...
     ad'*apppsa'*A2'*A1'*AT'-...
    sd*uz'*A1'*AT')*atil(uz)*(BTran(pd,A1*A2*atppp)*p+...
    AT*A1*A2*atpppsa*ad)+at'*atil(uz)*(BTran(pd,bp)*pd-...
    2*sd*BTran(pd,A1*uz)*p-s*BTran(pd,A1*uz)*pd+BTran(pd,A1*A2*appp)*pd+...
    MTran(p,pd)*A1*A2*apppsa*ad+BTran(pd,A1*A2*apppsa*ad)*p)
E2=[rd'*BTran(pd,ux)*p+ux'*AT'*BTran(pd,dpP0)*pd+...
    pd'*BTran(p,dpP0)'*BTran(pd,ux)*p;c2];

end

